apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcedesk
spec:
  selector:
    matchLabels:
      app: tcedesk
  replicas: 1
  template:
    metadata:
      labels:
        app: tcedesk
    spec:
      containers:
      - name: tcedesk
        image: mohankumarr2001/tce-desk-cutomer-care-registry:tce_desk_customer_care_registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: tcedesk-service
spec:
  type: NodePort
  selector:
    app: tcedesk
  
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080


